"use client";
import { useEffect, useRef, useState } from "react";
import { ShieldCheck, Sparkles, BriefcaseBusiness, Blocks, Layers3, FileText, Check, GitCompareArrows, X, PackageOpen, Eye, SlidersHorizontal, ArrowRight } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { products, niches, bundles, type Product, type Bundle, money } from "@/lib/catalog";
const icons = [Layers3, ShieldCheck, Sparkles, BriefcaseBusiness, Blocks];
const total = (bundle: Bundle) => bundle.products.reduce((sum, id) => sum + products.find(p => p.id === id)!.price, 0);
const compareRows: [string, (p: Product) => string][] = [["The job it helps with", p => p.solve], ["Designed for", p => p.audience], ["Planned contents", p => p.contents.join(" · ")], ["Proposed formats", p => p.formats.join(" + ")], ["Setup needed", p => p.setup], ["Placeholder price", p => `${money(p.price)} USD · one-time`]];

function WorkstackMark() {
  return <svg className="brand-symbol" viewBox="0 0 32 32" aria-hidden="true" fill="none"><path d="M4.5 12h13v13h-13zM8 12V9.5h6V12M7.5 17h7M7.5 21h5" stroke="#F7F5EF" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/><path d="M17.5 18.5h3.2l2.2-3.4M17.5 22h3.2l2.2 2" stroke="#55C9BF" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/><circle cx="24.5" cy="12" r="3.1" stroke="#D6AD60" strokeWidth="1.7"/><path d="M24.5 6.5c4 1.7 5.8 4.3 5 7.3-.6 2.6-2.6 4.2-5 4.9-2.4-.7-4.4-2.3-5-4.9-.8-3 1-5.6 5-7.3Z" stroke="#D6AD60" strokeWidth="1.2" opacity=".75"/></svg>;
}

export default function Home() {
  const dialogOrigin = useRef<HTMLElement | null>(null);
  const dockRef = useRef<HTMLDivElement | null>(null);
  function rememberDialogOrigin() { dialogOrigin.current = document.activeElement as HTMLElement; }
  function restoreDialogFocus(event: Event) {
    event.preventDefault();
    requestAnimationFrame(() => {
      if (document.querySelector('[role="dialog"]')) return;
      const origin = dialogOrigin.current;
      if (origin?.isConnected && !origin.matches(':disabled')) origin.focus();
      else (document.querySelector<HTMLButtonElement>('.clear-btn') ?? document.querySelector<HTMLElement>('#catalog'))?.focus();
    });
  }
  const [niche, setNiche] = useState("all");
  const [query, setQuery] = useState("");
  const searchRef = useRef<HTMLInputElement | null>(null);
  const [selected, setSelected] = useState<string[]>([]);
  const [detail, setDetail] = useState<Product | null>(null);
  const [bundle, setBundle] = useState<Bundle | null>(null);
  const [compareOpen, setCompareOpen] = useState(false);
  const hasSelection = selected.length > 0;
  useEffect(() => {
    const dock = dockRef.current;
    if (!hasSelection || !dock) return;
    const updateSpace = () => document.documentElement.style.setProperty('--compare-space', `${dock.getBoundingClientRect().height + 44}px`);
    updateSpace();
    const observer = new ResizeObserver(updateSpace);
    observer.observe(dock);
    return () => { observer.disconnect(); document.documentElement.style.removeProperty('--compare-space'); };
  }, [hasSelection]);
  const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  const matchesSearch = (p: Product) => {
    const text = [p.name, p.solve, p.audience, p.setup, ...p.contents, ...p.formats, niches.find(n => n.id === p.niche)?.label].join(" ").toLowerCase();
    return terms.every(term => text.includes(term));
  };
  const visible = products.filter(p => (niche === "all" || p.niche === niche) && matchesSearch(p));
  function resetFilters() { setNiche("all"); setQuery(""); searchRef.current?.focus(); }
  function removeSelection(id: string) {
    toggle(id);
    requestAnimationFrame(() => (document.querySelector<HTMLButtonElement>('.clear-btn') ?? document.querySelector<HTMLElement>('#catalog'))?.focus());
  }
  const compared = products.filter(p => selected.includes(p.id));
  const relevantBundles = bundles.filter(b => niche === "all" || b.niche === niche || b.niche === "all");
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(x => x !== id) : current.length < 3 ? [...current, id] : current); }
  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool: (tool: unknown, options: { signal: AbortSignal }) => unknown } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    try { Promise.resolve(context.registerTool({ name: "browse_toolkit_niche", title: "Browse a toolkit niche", description: "Filter the visible concept catalog by niche. Prices and contents are proposals; no purchase occurs.", inputSchema: { type: "object", properties: { niche: { type: "string", enum: niches.map(n => n.id) } }, required: ["niche"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (input: unknown) => {
      if (typeof input !== "object" || !input || Array.isArray(input)) throw new Error("Choose a valid niche.");
      const value = input as { niche?: string };
      if (!niches.some(n => n.id === value.niche) || Object.keys(value).some(k => k !== "niche")) throw new Error("Choose a valid niche.");
      setNiche(value.niche!);
      setQuery("");
      await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
      return { niche: value.niche, products: products.filter(p => value.niche === "all" || p.niche === value.niche).map(p => ({ id: p.id, name: p.name, placeholderPriceUSD: p.price })) };
    } }, { signal: lifecycle.signal })).catch(() => {}); } catch {}
    return () => lifecycle.abort();
  }, []);
  return <>
    <a className="skip-link" href="#catalog">Skip to catalog</a>
    <header className="site-header" id="top"><div className="shell header-inner"><a href="#top" className="brand" aria-label="Workstack home"><span className="brand-mark"><WorkstackMark /></span>workstack<span className="brand-sub">/ tools</span></a><nav aria-label="Main navigation"><a href="#catalog">Toolkits</a><a href="#bundles">Bundles</a><a href="#approach">The approach</a><a href="#availability">Availability</a></nav><span className="concept-badge"><Eye size={15} /> Concept storefront</span></div></header>
    <main>
      <section className="hero-section shell" aria-labelledby="main-title"><div className="hero-copy"><p className="eyebrow">CYBERSECURITY · AI · BUSINESS OPERATIONS</p><h1 id="main-title">Turn everyday tasks into smarter business systems.</h1><p className="intro-description">Explore practical cybersecurity, AI governance, and workflow toolkits designed to simplify complex work.</p><div className="hero-actions"><a className="hero-primary" href="#catalog">Explore Toolkits <ArrowRight size={18} aria-hidden="true" /></a><a className="hero-secondary" href="#comparison"><GitCompareArrows size={18} aria-hidden="true" />Compare Solutions</a></div><p className="hero-status">Proposed catalog · Prices are placeholders · No checkout available</p></div><div className="hero-artwork"><picture><source type="image/webp" srcSet="/images/workstack-story-480.webp 480w, /images/workstack-story-960.webp 960w, /images/workstack-story-1360.webp 1360w, /images/workstack-story-1672.webp 1672w" sizes="(max-width: 800px) 100vw, (max-width: 1200px) 58vw, 64vw" /><img src="/images/workstack-story.png" width="1672" height="941" alt="Digital toolkits connected through an AI assistant to cybersecurity, AI, and organized business workflows." fetchPriority="high" loading="eager" decoding="async" /></picture></div></section>
      <section className="comparison-intro shell" id="comparison" aria-labelledby="comparison-title"><div><p className="eyebrow">SOLUTION COMPARISON</p><h2 id="comparison-title">Compare tools by purpose and fit.</h2></div><p>Explore cybersecurity, AI, and business operations resources side by side.</p></section>
      <section className="catalog-section shell" id="catalog" tabIndex={-1} aria-labelledby="catalog-title"><div className="section-heading"><div><p className="eyebrow">THE TOOLKIT CATALOG</p><h2 id="catalog-title">Good work starts here.</h2></div><span className="section-meta">{products.length} proposed products <span aria-hidden="true">/</span> {niches.length - 1} niches</span></div>
        <div className="catalog-search"><label htmlFor="tool-search">Find a toolkit for your task</label><div><input ref={searchRef} id="tool-search" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Try threat modeling, AI pilot, or handoff" aria-describedby="search-help" />{query && <button onClick={() => { setQuery(""); searchRef.current?.focus(); }}>Clear search</button>}</div><p id="search-help">Search names, tasks, audiences, formats, and planned contents within the selected category.</p></div>
        <div role="group" className="filter-list" aria-label="Filter products by niche">{niches.map((n, i) => { const Icon = icons[i]; return <button key={n.id} className={`filter ${niche === n.id ? "filter-active" : ""}`} aria-pressed={niche === n.id} onClick={() => setNiche(n.id)}><Icon size={17} /><span>{n.label}</span><span className="filter-count">{n.id === "all" ? products.length : products.filter(p => p.niche === n.id).length}</span></button>; })}</div>
        <div className="catalog-status"><p><SlidersHorizontal size={15} /><span aria-live="polite">{visible.length} matching tools {niche === "all" ? "across all collections" : `in ${niches.find(n => n.id === niche)?.label}`}</span></p><p className="price-note">All prices are USD placeholders</p></div>
        {visible.length === 0 && <div className="empty-results"><h3>No matching toolkits</h3><p>Try a broader task or a different category.</p><button className="preview-btn" onClick={resetFilters}>Reset search and categories</button></div>}
        <div className="product-grid">{visible.map(p => { const ni = niches.findIndex(n => n.id === p.niche); const Icon = icons[ni]; const chosen = selected.includes(p.id); return <article className={`product-card ${chosen ? "is-selected" : ""}`} key={p.id}><div className={`product-cover tone-${p.niche}`}><div className="cover-top"><span className="cover-icon"><Icon size={21} /></span><span className="cover-type">{p.type}</span></div><div className="cover-file"><FileText size={15} /><span>{p.file}</span><span className="file-extension">{p.formats[0]}</span></div></div><div className="product-body"><p className={`category-label text-${p.niche}`}>{niches[ni].label}</p><h3>{p.name}</h3><p className="product-description">{p.solve}</p><p className="product-audience"><strong>For:</strong> {p.audience}</p><div className="product-formats"><span>{p.contents.length} planned resources</span><span aria-hidden="true">·</span><span>{p.formats.join(" + ")}</span></div><div className="product-action"><div className="price"><b>{money(p.price)}</b><span>USD placeholder</span></div><button className="preview-btn" onClick={() => { rememberDialogOrigin(); setDetail(p); }} aria-label={`Preview ${p.name}`}>Preview toolkit</button></div></div><div className="card-compare"><Checkbox id={`compare-${p.id}`} checked={chosen} disabled={!chosen && selected.length === 3} onCheckedChange={() => toggle(p.id)} aria-label={`Compare ${p.name}`} /><label htmlFor={`compare-${p.id}`}>Compare this tool</label></div></article>; })}</div>
        <p className="catalog-footnote">Concept catalog: products are in development. Previews show proposed contents and illustrative samples. Checkout is unavailable.</p>
      </section>
      <section className="bundle-section shell" id="bundles" aria-labelledby="bundle-title"><div className="section-heading"><div><p className="eyebrow">BETTER TOGETHER</p><h2 id="bundle-title">Go from a tool to a toolkit.</h2></div><p className="section-meta">Bundles follow the category filter; search applies to individual tools.</p></div><div className="bundle-grid">{relevantBundles.map(b => <article className={`bundle-card ${b.niche === "all" ? "complete-bundle" : ""}`} key={b.id}><div className="bundle-top"><PackageOpen size={23} /><span>{b.niche === "all" ? "COMPLETE COLLECTION" : "NICHE BUNDLE"}</span></div><h3>{b.name}</h3><p>{b.description}</p><ul className="bundle-tool-names">{b.products.map(id => <li key={id}>{products.find(p => p.id === id)!.name}</li>)}</ul><div className="bundle-includes">{b.products.length} tools <span aria-hidden="true">·</span> {b.products.reduce((s, id) => s + products.find(p => p.id === id)!.contents.length, 0)} planned resources</div><div className="bundle-bottom"><div className="price"><b>{money(b.price)}</b><span>Placeholder · one-time</span></div><button className="bundle-btn" onClick={() => { rememberDialogOrigin(); setBundle(b); }} aria-label={`View ${b.name} contents`}>View contents</button></div><p className="individual-price">Individual placeholder total: {money(total(b))}</p></article>)}</div></section>
      <section className="approach-section shell" id="approach" aria-labelledby="approach-title"><div className="approach-intro"><p className="eyebrow">THE PRODUCT-LINE APPROACH</p><h2 id="approach-title">Start focused.<br />Grow your system.</h2><p>Practical resources for reviewing security risks, planning responsible AI, and making business processes easier to own and review.</p></div><div className="approach-steps">{[["01", "Individual tools", "Choose a specific job: review an app, plan an AI pilot, or review an operational risk."], ["02", "Niche bundles", "Pair complementary tools for the next step in the same professional workflow."], ["03", "The complete collection", "Connect security, AI safety, and business operations with clear ownership and structured handoffs."]].map(([num, name, desc]) => <div key={num}><span className="step-number">{num}</span><div><h3>{name}</h3><p>{desc}</p></div></div>)}</div></section>
      <section className="availability-section shell" id="availability" aria-labelledby="availability-title"><p className="eyebrow">BEFORE YOU PLAN A PURCHASE</p><h2 id="availability-title">Availability and policies</h2><p>Workstack is a proposed digital toolkit business. Every listed product, bundle, price, format, and sample is a placeholder for review. Plugins are concepts, with no confirmed platform or live integration.</p><p>Release dates, final deliverables, compatibility, licensing, refunds, support, updates, and privacy and purchase terms are not yet finalized. Checkout and downloads are unavailable.</p><p>These proposed resources do not promise security, compliance, or business outcomes.</p></section>
    </main>
    <footer className="site-footer"><div className="shell footer-inner"><a href="#top" className="brand"><span className="brand-mark"><WorkstackMark /></span>workstack<span className="brand-sub">/ tools</span></a><p>Working brand · Proposed catalog and pricing · No checkout</p><a href="#catalog">Back to catalog</a></div></footer>
    {selected.length > 0 && <div ref={dockRef} className="compare-dock" role="region" aria-label="Selected tools for comparison"><div className="dock-title"><GitCompareArrows size={20} /><div><strong>{selected.length} of 3 tools selected</strong><span>{selected.length < 2 ? "Select one more tool to compare" : selected.length === 3 ? "Limit reached. Remove a tool to choose another." : "Ready to compare. Add one more if you like."}</span></div></div><div className="dock-chips">{compared.map(p => <button key={p.id} onClick={() => removeSelection(p.id)} title={p.name} aria-label={`Remove ${p.name} from comparison`}><span>{p.name}</span><X size={14} /></button>)}</div><button className="clear-btn" onClick={() => { setSelected([]); requestAnimationFrame(() => document.querySelector<HTMLElement>("#catalog")?.focus()); }}>Clear</button><button className="compare-btn" disabled={selected.length < 2} onClick={() => { rememberDialogOrigin(); setCompareOpen(true); }}>Compare tools</button><span className="sr-only" aria-live="polite">{selected.length} tools selected. {selected.length === 3 ? "Maximum reached. Remove a tool to choose another." : ""}</span></div>}
    <Dialog open={!!detail} onOpenChange={open => { if (!open) setDetail(null); }}><DialogContent onCloseAutoFocus={restoreDialogFocus} className="tool-dialog">{detail && <><p className="eyebrow">TOOLKIT PREVIEW / {niches.find(n => n.id === detail.niche)?.label}</p><DialogTitle className="modal-title">{detail.name}</DialogTitle><DialogDescription className="modal-description">{detail.solve}</DialogDescription><div className="detail-summary"><div><span>Designed for</span><b>{detail.audience}</b></div><div><span>Proposed formats</span><b>{detail.formats.join(" / ")}</b></div><div><span>Placeholder price</span><b>{money(detail.price)} USD</b></div></div><h3 className="modal-heading">Setup and compatibility</h3><p className="setup-note">{detail.setup}</p><h3 className="modal-heading">What’s planned inside</h3><ul className="contents-list">{detail.contents.map(c => <li key={c}><Check size={16} />{c}</li>)}</ul><div className="sample-preview"><div className="sample-header"><FileText size={16} /><span>Illustrative sample</span><span>{detail.file}</span></div>{detail.sample.map(([label, value]) => <div className="sample-row" key={label}><span>{label}</span><b>{value}</b></div>)}</div><p className="modal-note">This is a concept preview. Final files, compatibility, licensing, and price will be confirmed before sale.</p></>}</DialogContent></Dialog>
    <Dialog open={!!bundle} onOpenChange={open => { if (!open) setBundle(null); }}><DialogContent onCloseAutoFocus={restoreDialogFocus} className="tool-dialog">{bundle && <><p className="eyebrow">BUNDLE CONTENTS / PROPOSED COLLECTION</p><DialogTitle className="modal-title">{bundle.name}</DialogTitle><DialogDescription className="modal-description">{bundle.description}</DialogDescription><div className="bundle-price-summary"><div className="price"><b>{money(bundle.price)}</b><span>USD placeholder · one-time</span></div><p>Individual placeholder total<br /><strong>{money(total(bundle))}</strong></p></div><div className="bundle-content-list">{bundle.products.map(id => { const p = products.find(p => p.id === id)!; return <div key={id}><div><h3>{p.name}</h3><p>{p.contents.length} planned resources · {p.formats.join(" + ")}</p></div><button onClick={() => { setBundle(null); setDetail(p); }} aria-label={`Preview ${p.name} from bundle`}>Preview</button></div>; })}</div><p className="modal-note">All listed tools are included in the proposed bundle. Pricing and contents are placeholders; purchase and download are unavailable.</p></>}</DialogContent></Dialog>
    <Dialog open={compareOpen} onOpenChange={setCompareOpen}><DialogContent onCloseAutoFocus={restoreDialogFocus} className="compare-dialog"><p className="eyebrow">SIDE-BY-SIDE</p><DialogTitle className="modal-title">Find the right fit.</DialogTitle><DialogDescription className="modal-description">Compare the job, audience, and proposed resources. All prices are USD placeholders.</DialogDescription><p className="comparison-hint" id="comparison-help">On smaller screens, scroll sideways to see all selected tools. Keyboard users can focus the table area and use the arrow keys.</p><div className="comparison-scroll" role="region" aria-label="Toolkit comparison table" aria-describedby="comparison-help" tabIndex={0}><Table className="comparison-table"><TableHeader><TableRow><TableHead scope="col">What matters</TableHead>{compared.map(p => <TableHead scope="col" key={p.id}>{p.name}<button className="comparison-remove" aria-label={`Remove ${p.name}`} onClick={() => { toggle(p.id); if (selected.length <= 2) setCompareOpen(false); }}><X size={14} /></button></TableHead>)}</TableRow></TableHeader><TableBody>{compareRows.map(([label, getter]) => <TableRow key={label}><TableHead scope="row">{label}</TableHead>{compared.map(p => <TableCell key={p.id}>{getter(p)}</TableCell>)}</TableRow>)}</TableBody></Table></div><p className="modal-note">Contents are proposals. No performance, compliance, or customer results are claimed.</p></DialogContent></Dialog>
  </>;
}
