"use client";
import { useEffect, useState } from "react";
import { ShieldCheck, Sparkles, Building2, BriefcaseBusiness, Blocks, Layers3, FileText, Check, GitCompareArrows, X, PackageOpen, Eye, SlidersHorizontal } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { products, niches, bundles, type Product, type Bundle, money } from "@/lib/catalog";
const icons = [Layers3, ShieldCheck, Sparkles, Building2, BriefcaseBusiness, Blocks];
const total = (bundle: Bundle) => bundle.products.reduce((sum, id) => sum + products.find(p => p.id === id)!.price, 0);
const compareRows: [string, (p: Product) => string][] = [["The job it helps with", p => p.solve], ["Designed for", p => p.audience], ["Planned contents", p => p.contents.join(" · ")], ["Proposed formats", p => p.formats.join(" + ")], ["Setup needed", p => p.setup], ["Placeholder price", p => `${money(p.price)} USD · one-time`]];

export default function Home() {
  const [niche, setNiche] = useState("all");
  const [selected, setSelected] = useState<string[]>([]);
  const [detail, setDetail] = useState<Product | null>(null);
  const [bundle, setBundle] = useState<Bundle | null>(null);
  const [compareOpen, setCompareOpen] = useState(false);
  const visible = products.filter(p => niche === "all" || p.niche === niche);
  const compared = products.filter(p => selected.includes(p.id));
  const relevantBundles = bundles.filter(b => niche === "all" || b.niche === niche || b.niche === "all");
  function toggle(id: string) { setSelected(current => current.includes(id) ? current.filter(x => x !== id) : current.length < 3 ? [...current, id] : current); }
  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool: (tool: unknown, options: { signal: AbortSignal }) => unknown } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    try { Promise.resolve(context.registerTool({ name: "browse_toolkit_niche", title: "Browse a toolkit niche", description: "Filter the visible concept catalog by niche. Prices and contents are proposals; no purchase occurs.", inputSchema: { type: "object", properties: { niche: { type: "string", enum: niches.map(n => n.id) } }, required: ["niche"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute: async (input: unknown) => {
      if (typeof input !== "object" || !input || Array.isArray(input)) throw new Error("Choose a valid niche.");
      const value = input as { niche?: string };
      if (!niches.some(n => n.id === value.niche) || Object.keys(value).some(k => k !== "niche")) throw new Error("Choose a valid niche.");
      setNiche(value.niche!);
      await new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
      return { niche: value.niche, products: products.filter(p => value.niche === "all" || p.niche === value.niche).map(p => ({ id: p.id, name: p.name, placeholderPriceUSD: p.price })) };
    } }, { signal: lifecycle.signal })).catch(() => {}); } catch {}
    return () => lifecycle.abort();
  }, []);
  return <>
    <a className="skip-link" href="#catalog">Skip to catalog</a>
    <header className="site-header"><div className="shell header-inner"><a href="#" className="brand" aria-label="Workstack home"><span className="brand-mark"><Layers3 size={23} /></span>workstack<span className="brand-sub">/ tools</span></a><nav aria-label="Main navigation"><a className="nav-active" href="#catalog">Toolkits</a><a href="#bundles">Bundles</a><a href="#approach">The approach</a></nav><span className="concept-badge"><Eye size={15} /> Concept storefront</span></div></header>
    <main>
      <section className="intro shell" aria-labelledby="main-title"><div><p className="eyebrow">PURPOSE-BUILT DIGITAL TOOLS</p><h1 id="main-title">A better starting point<br />for the work you do.</h1><p className="intro-description">Focused toolkits, editable templates, and workflow plugins.<br className="desktop-break" /> Find the right tool. Build your own system.</p></div><div className="intro-aside"><div className="intro-aside-top"><Layers3 size={19} /><span>Small tools. Connected systems.</span></div><div className="stack-path"><span><b>01</b> Pick a task</span><span><b>02</b> Explore a toolkit</span><span><b>03</b> Build with a bundle</span></div><p>Five focused collections. One practical product line.</p></div></section>
      <section className="catalog-section shell" id="catalog" aria-labelledby="catalog-title"><div className="section-heading"><div><p className="eyebrow">THE TOOLKIT CATALOG</p><h2 id="catalog-title">Good work starts here.</h2></div><span className="section-meta">10 proposed products <span aria-hidden="true">/</span> 5 niches</span></div>
        <div className="filter-list" aria-label="Filter products by niche">{niches.map((n, i) => { const Icon = icons[i]; return <button key={n.id} className={`filter ${niche === n.id ? "filter-active" : ""}`} aria-pressed={niche === n.id} onClick={() => setNiche(n.id)}><Icon size={17} /><span>{n.label}</span><span className="filter-count">{n.id === "all" ? products.length : products.filter(p => p.niche === n.id).length}</span></button>; })}</div>
        <div className="catalog-status"><p><SlidersHorizontal size={15} /><span aria-live="polite">{visible.length} tools {niche === "all" ? "across all collections" : `in ${niches.find(n => n.id === niche)?.label}`}</span></p><p className="price-note">All prices are USD placeholders</p></div>
        <div className="product-grid">{visible.map(p => { const ni = niches.findIndex(n => n.id === p.niche); const Icon = icons[ni]; const chosen = selected.includes(p.id); return <article className={`product-card ${chosen ? "is-selected" : ""}`} key={p.id}><div className={`product-cover tone-${p.niche}`}><div className="cover-top"><span className="cover-icon"><Icon size={21} /></span><span className="cover-type">{p.type}</span></div><div className="cover-file"><FileText size={15} /><span>{p.file}</span><span className="file-extension">{p.formats[0]}</span></div></div><div className="product-body"><p className={`category-label text-${p.niche}`}>{niches[ni].label}</p><h3>{p.name}</h3><p className="product-description">{p.solve}</p><div className="product-formats"><span>{p.contents.length} planned resources</span><span aria-hidden="true">·</span><span>{p.formats.join(" + ")}</span></div><div className="product-action"><div className="price"><b>{money(p.price)}</b><span>Placeholder</span></div><button className="preview-btn" onClick={() => setDetail(p)} aria-label={`Preview ${p.name}`}>Preview toolkit</button></div></div><div className="card-compare"><Checkbox id={`compare-${p.id}`} checked={chosen} disabled={!chosen && selected.length === 3} onCheckedChange={() => toggle(p.id)} aria-label={`Compare ${p.name}`} /><label htmlFor={`compare-${p.id}`}>Compare this tool</label></div></article>; })}</div>
        <p className="catalog-footnote">Concept catalog: products are in development. Previews show proposed contents and illustrative samples. Checkout is unavailable.</p>
      </section>
      <section className="bundle-section shell" id="bundles" aria-labelledby="bundle-title"><div className="section-heading"><div><p className="eyebrow">BETTER TOGETHER</p><h2 id="bundle-title">Go from a tool to a toolkit.</h2></div><p className="section-meta">Connected resources for a complete workflow</p></div><div className="bundle-grid">{relevantBundles.map(b => <article className={`bundle-card ${b.niche === "all" ? "complete-bundle" : ""}`} key={b.id}><div className="bundle-top"><PackageOpen size={23} /><span>{b.niche === "all" ? "COMPLETE COLLECTION" : "NICHE BUNDLE"}</span></div><h3>{b.name}</h3><p>{b.description}</p><div className="bundle-includes">{b.products.length} tools <span aria-hidden="true">·</span> {b.products.reduce((s, id) => s + products.find(p => p.id === id)!.contents.length, 0)} planned resources</div><div className="bundle-bottom"><div className="price"><b>{money(b.price)}</b><span>Placeholder · one-time</span></div><button className="bundle-btn" onClick={() => setBundle(b)} aria-label={`View ${b.name} contents`}>View contents</button></div><p className="individual-price">Individual placeholder total: {money(total(b))}</p></article>)}</div></section>
      <section className="approach-section shell" id="approach" aria-labelledby="approach-title"><div className="approach-intro"><p className="eyebrow">THE PRODUCT-LINE APPROACH</p><h2 id="approach-title">Start focused.<br />Grow your system.</h2><p>A family of products built around recurring work, with a clear path from one useful resource to a coordinated collection.</p></div><div className="approach-steps">{[["01", "Individual tools", "Choose a specific job: review an app, plan an AI pilot, or organize a transaction."], ["02", "Niche bundles", "Pair complementary tools for the next step in the same professional workflow."], ["03", "The complete collection", "Bring the five product lines together for work that spans teams and disciplines."]].map(([num, name, desc]) => <div key={num}><span className="step-number">{num}</span><div><h3>{name}</h3><p>{desc}</p></div></div>)}</div></section>
    </main>
    <footer className="site-footer"><div className="shell footer-inner"><a href="#" className="brand"><Layers3 size={21} />workstack<span className="brand-sub">/ tools</span></a><p>Working brand · Proposed catalog and pricing · No checkout</p><a href="#catalog">Back to catalog</a></div></footer>
    {selected.length > 0 && <div className="compare-dock" role="region" aria-label="Selected tools for comparison"><div className="dock-title"><GitCompareArrows size={20} /><div><strong>{selected.length} of 3 tools selected</strong><span>Select at least 2 to compare</span></div></div><div className="dock-chips">{compared.map(p => <button key={p.id} onClick={() => toggle(p.id)} aria-label={`Remove ${p.name} from comparison`}><span>{p.name}</span><X size={14} /></button>)}</div><button className="clear-btn" onClick={() => setSelected([])}>Clear</button><button className="compare-btn" disabled={selected.length < 2} onClick={() => setCompareOpen(true)}>Compare tools</button><span className="sr-only" aria-live="polite">{selected.length} tools selected. {selected.length === 3 ? "Maximum reached. Remove a tool to choose another." : ""}</span></div>}
    <Dialog open={!!detail} onOpenChange={open => { if (!open) setDetail(null); }}><DialogContent className="tool-dialog">{detail && <><p className="eyebrow">TOOLKIT PREVIEW / {niches.find(n => n.id === detail.niche)?.label}</p><DialogTitle className="modal-title">{detail.name}</DialogTitle><DialogDescription className="modal-description">{detail.solve}</DialogDescription><div className="detail-summary"><div><span>Designed for</span><b>{detail.audience}</b></div><div><span>Proposed formats</span><b>{detail.formats.join(" / ")}</b></div><div><span>Placeholder price</span><b>{money(detail.price)} USD</b></div></div><h3 className="modal-heading">What’s planned inside</h3><ul className="contents-list">{detail.contents.map(c => <li key={c}><Check size={16} />{c}</li>)}</ul><div className="sample-preview"><div className="sample-header"><FileText size={16} /><span>Illustrative sample</span><span>{detail.file}</span></div>{detail.sample.map(([label, value]) => <div className="sample-row" key={label}><span>{label}</span><b>{value}</b></div>)}</div><p className="modal-note">This is a concept preview. Final files, compatibility, licensing, and price will be confirmed before sale.</p></>}</DialogContent></Dialog>
    <Dialog open={!!bundle} onOpenChange={open => { if (!open) setBundle(null); }}><DialogContent className="tool-dialog">{bundle && <><p className="eyebrow">BUNDLE CONTENTS / PROPOSED COLLECTION</p><DialogTitle className="modal-title">{bundle.name}</DialogTitle><DialogDescription className="modal-description">{bundle.description}</DialogDescription><div className="bundle-price-summary"><div className="price"><b>{money(bundle.price)}</b><span>USD placeholder · one-time</span></div><p>Individual placeholder total<br /><strong>{money(total(bundle))}</strong></p></div><div className="bundle-content-list">{bundle.products.map(id => { const p = products.find(p => p.id === id)!; return <div key={id}><div><h3>{p.name}</h3><p>{p.contents.length} planned resources · {p.formats.join(" + ")}</p></div><button onClick={() => { setBundle(null); setDetail(p); }} aria-label={`Preview ${p.name} from bundle`}>Preview</button></div>; })}</div><p className="modal-note">All listed tools are included in the proposed bundle. Pricing and contents are placeholders; purchase and download are unavailable.</p></>}</DialogContent></Dialog>
    <Dialog open={compareOpen} onOpenChange={setCompareOpen}><DialogContent className="compare-dialog"><p className="eyebrow">SIDE-BY-SIDE</p><DialogTitle className="modal-title">Find the right fit.</DialogTitle><DialogDescription className="modal-description">Compare the job, audience, and proposed resources. All prices are USD placeholders.</DialogDescription><Table className="comparison-table"><TableHeader><TableRow><TableHead scope="col">What matters</TableHead>{compared.map(p => <TableHead scope="col" key={p.id}>{p.name}<button className="comparison-remove" aria-label={`Remove ${p.name}`} onClick={() => { toggle(p.id); if (selected.length <= 2) setCompareOpen(false); }}><X size={14} /></button></TableHead>)}</TableRow></TableHeader><TableBody>{compareRows.map(([label, getter]) => <TableRow key={label}><TableHead scope="row">{label}</TableHead>{compared.map(p => <TableCell key={p.id}>{getter(p)}</TableCell>)}</TableRow>)}</TableBody></Table><p className="modal-note">Contents are proposals. No performance, compliance, or customer results are claimed.</p></DialogContent></Dialog>
  </>;
}
