export type Product = { id: string; niche: string; name: string; type: string; solve: string; audience: string; price: number; formats: string[]; file: string; setup: string; contents: string[]; sample: [string, string][] };
export type Bundle = { id: string; niche: string; name: string; description: string; price: number; products: string[] };
export const money = (amount: number) => `$${amount}`;
export const niches = [{ id: "all", label: "All tools" }, { id: "security", label: "Cybersecurity & AppSec" }, { id: "ai", label: "AI & governance" }, { id: "estate", label: "Real estate" }, { id: "business", label: "Business operations" }, { id: "plugins", label: "Workflow plugins" }];
export const products: Product[] = [
  { id: "app-review", niche: "security", name: "Application Review Kit", type: "REVIEW TOOLKIT", solve: "Give application reviews a consistent scope, checklist, and remediation handoff.", audience: "Application security engineers and software teams", price: 79, formats: ["MD", "XLSX", "DOCX"], file: "application_review.md", setup: "Adapt the scope and controls to your application.", contents: ["Review intake form", "Scope and data-flow worksheet", "Authentication review checklist", "Findings report template", "Severity decision worksheet", "Remediation tracker"], sample: [["Review area", "Session handling"], ["Question", "How are sessions created, expired, and revoked?"], ["Evidence", "Record configuration and relevant code references."], ["Next step", "Assign an owner and document open findings."]] },
  { id: "ai-pilot", niche: "ai", name: "AI Implementation Planner", type: "IMPLEMENTATION SYSTEM", solve: "Turn an AI use case into a scoped pilot with owners, evaluation criteria, and rollout gates.", audience: "AI implementation leads and business teams", price: 79, formats: ["XLSX", "DOCX"], file: "pilot_readiness.xlsx", setup: "Define the use case, data sources, and evaluation targets.", contents: ["Use-case scoring sheet", "Pilot charter", "Data-readiness checklist", "Evaluation plan", "Rollout gate worksheet", "Ownership matrix"], sample: [["Use case", "Internal knowledge assistant"], ["Data owner", "To be assigned"], ["Evaluation", "Define an answer-quality review set."], ["Launch gate", "Approve data access and fallback behavior."]] },
  { id: "estate-transaction", niche: "estate", name: "Transaction Workflow System", type: "PROFESSIONAL SYSTEM", solve: "Keep transaction milestones, documents, and client updates in one organized workflow.", audience: "Real-estate agents and transaction coordinators", price: 69, formats: ["XLSX", "DOCX"], file: "transaction_tracker.xlsx", setup: "Add local requirements, contract dates, and brokerage procedures.", contents: ["Transaction milestone tracker", "Document inventory", "Client update templates", "Responsibility checklist", "Closing handoff worksheet"], sample: [["Milestone", "Inspection coordination"], ["Due date", "Enter contract-specific date"], ["Owner", "Assign responsible contact"], ["Update", "Confirm next action with the client."]] },
  { id: "threat-model", niche: "security", name: "Threat Modeling Workbook", type: "SECURITY WORKBOOK", solve: "Map trust boundaries, discuss abuse cases, and record risks before a design ships.", audience: "Security architects and product engineering teams", price: 59, formats: ["XLSX", "MD"], file: "threat_register.xlsx", setup: "Bring your system diagram and identify assets and trust boundaries.", contents: ["System and asset inventory", "Trust-boundary worksheet", "Abuse-case prompts", "Threat and risk register", "Design review summary"], sample: [["Asset", "Customer conversation data"], ["Scenario", "A session accesses another user’s conversation."], ["Control to review", "Server-side authorization on every request"], ["Decision", "Record evidence, owner, and residual risk."]] },
  { id: "ai-governance", niche: "ai", name: "AI Governance Starter Kit", type: "GOVERNANCE TEMPLATES", solve: "Make AI ownership, risk decisions, and review expectations explicit across your team.", audience: "Governance, security, and business owners", price: 89, formats: ["DOCX", "XLSX"], file: "ai_system_inventory.xlsx", setup: "Tailor the templates to your organization and applicable obligations.", contents: ["AI system inventory", "Risk assessment worksheet", "Acceptable-use policy draft", "Approval and exception log", "Human oversight checklist", "Vendor review questionnaire"], sample: [["System", "Internal writing assistant"], ["Accountable owner", "To be assigned"], ["Data classification", "Define allowed and restricted inputs."], ["Oversight", "Document when human review is required."]] },
  { id: "estate-client", niche: "estate", name: "Client Pipeline & Follow-up Kit", type: "CLIENT OPERATIONS", solve: "Organize prospects, next actions, and client communications without losing the thread.", audience: "Independent agents and small real-estate teams", price: 49, formats: ["XLSX", "DOCX"], file: "client_pipeline.xlsx", setup: "Define your pipeline stages and adapt messages to brokerage guidance.", contents: ["Client pipeline tracker", "Buyer and seller intake sheets", "Follow-up message templates", "Weekly pipeline review worksheet"], sample: [["Stage", "Initial consultation"], ["Next action", "Confirm goals and preferred timeline."], ["Due date", "Enter agreed follow-up date"], ["Notes", "Record consent and communication preferences."]] },
  { id: "sop", niche: "business", name: "SOP & Handoff Builder", type: "OPERATIONS TOOLKIT", solve: "Document repeatable work so a task has clear steps, ownership, and a useful handoff.", audience: "Small-business owners and operations managers", price: 49, formats: ["DOCX", "XLSX"], file: "process_handoff.docx", setup: "Choose a recurring process and assign the owner and reviewer.", contents: ["SOP template", "Process inventory", "Role and responsibility matrix", "Handoff checklist", "Change and review log"], sample: [["Process", "Monthly supplier review"], ["Owner", "Assign process owner"], ["Inputs", "Invoice log and supplier contacts"], ["Completion", "Record issues, decisions, and next actions."]] },
  { id: "business-review", niche: "business", name: "Business Review Dashboard", type: "OPERATIONS WORKBOOK", solve: "Bring recurring tasks, operating measures, and decisions into a structured weekly review.", audience: "Small-business operators and team leads", price: 59, formats: ["XLSX", "DOCX"], file: "weekly_review.xlsx", setup: "Select relevant measures and enter your own operating data.", contents: ["Weekly review workbook", "Operating measures tracker", "Action and owner log", "Meeting agenda template", "Decision register"], sample: [["Measure", "Open operational tasks"], ["Source", "Your team’s action tracker"], ["Review", "Discuss overdue items and dependencies."], ["Decision", "Assign the next action and a due date."]] },
  { id: "issue-plugin", niche: "plugins", name: "Finding-to-Issue Plugin", type: "PLUGIN CONCEPT", solve: "Plan a repeatable handoff from a reviewed security finding to a trackable engineering issue.", audience: "Security teams and issue-tracker administrators", price: 39, formats: ["PLUGIN", "MD"], file: "finding_to_issue.config", setup: "Planned integration; target platform, permissions, and installation are unconfirmed.", contents: ["Proposed finding-to-issue mapping", "Issue field configuration guide", "Permissions checklist", "Example payload specification"], sample: [["Source field", "Finding summary"], ["Target field", "Issue title"], ["Required context", "Evidence, owner, and remediation guidance"], ["Integration status", "Concept only; platform not yet selected."]] },
  { id: "handoff-plugin", niche: "plugins", name: "Workflow Handoff Plugin", type: "PLUGIN CONCEPT", solve: "Plan structured task handoffs with the context, owner, and completion criteria attached.", audience: "Operations teams and workflow administrators", price: 39, formats: ["PLUGIN", "MD"], file: "handoff_rules.config", setup: "Planned integration; target platform, permissions, and installation are unconfirmed.", contents: ["Proposed handoff rules", "Owner and status mapping", "Completion checklist specification", "Configuration guide"], sample: [["Trigger", "Task enters review"], ["Context", "Attach checklist and supporting references."], ["Owner", "Assign a designated reviewer."], ["Integration status", "Concept only; no live automation."]] }
];
export const bundles: Bundle[] = [
  { id: "secure", niche: "security", name: "Secure Delivery Bundle", description: "Connect design risks, application reviews, and remediation tracking.", price: 119, products: ["app-review", "threat-model"] },
  { id: "responsible-ai", niche: "ai", name: "Responsible AI Bundle", description: "Pair a practical pilot plan with ownership, oversight, and risk review.", price: 139, products: ["ai-pilot", "ai-governance"] },
  { id: "agent-ops", niche: "estate", name: "Agent Operations Bundle", description: "Connect the client pipeline to the transaction and closing workflow.", price: 99, products: ["estate-transaction", "estate-client"] },
  { id: "business-ops", niche: "business", name: "Business Systems Bundle", description: "Pair repeatable processes with a regular operating review.", price: 89, products: ["sop", "business-review"] },
  { id: "workflow", niche: "plugins", name: "Workflow Extensions Bundle", description: "Explore two specialized plugin concepts for structured team handoffs.", price: 59, products: ["issue-plugin", "handoff-plugin"] },
  { id: "complete", niche: "all", name: "The Workstack Collection", description: "All five product lines, together. A proposed library for work across disciplines.", price: 399, products: products.map(p => p.id) }
];
